" Basic
set nocompatible
set encoding=utf-8
set wrap
set number relativenumber
set laststatus=2
set hlsearch
set incsearch

" Typing
set tabstop=8
set expandtab
set shiftwidth=8
set softtabstop=8

" Code
syntax on

" Temp
nnoremap <Up> <NOP>
inoremap <Up> <NOP>
nnoremap <Down> <NOP>
inoremap <Down> <NOP>
nnoremap <Left> <NOP>
inoremap <Left> <NOP>
nnoremap <Right> <NOP>
inoremap <Right> <NOP>

" Non hardcoded vimrc directory path
let data_dir = fnamemodify(resolve(expand('<sfile>:p')), ':h')

" Install vim-plug if not found
if empty(glob(data_dir . '/autoload/plug.vim'))
  silent execute '!curl -fLo '.data_dir.'/autoload/plug.vim --create-dirs  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

call plug#begin()

" List your plugins here

call plug#end()
